choonz/urls.py
from django.urls import path
from choonz import views
from choonz.templatetags import choonz_template_tags
from choonz.views import AboutView, AddPlaylistView, IndexView, PlaylistRatingView, ShowPlaylistView, SearchSpotifyView,\
    RegisterProfileView, ProfileView, ListPlaylistView, TagSuggestionView, PlaylistEditorView, \
    AddSongView, ImportPlaylistView, RemoveSongView, PlaylistSuggestionView, DeletePlaylistView, \
    AddSongDetailView
# AddPageView,GoToView, SearchAddPage LikePlaylistView, 


app_name = 'choonz'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('about/', views.AboutView.as_view(), name='about'),
    path('contact/', views.ContactView.as_view(), name='contact'),
    path('add_playlist/', views.AddPlaylistView.as_view(), name='add_playlist'),
    path('list_playlists/', views.ListPlaylistView.as_view(), name='list_playlists'),
    path('playlist/<slug:playlist_name_slug>/', views.ShowPlaylistView.as_view(), name='show_playlist'),
    path('playlist/<slug:playlist_name_slug>/rate_playlist/', views.PlaylistRatingView.as_view(), name='rate_playlist'),
    path('playlist/<slug:playlist_name_slug>/edit_playlist/', views.PlaylistEditorView.as_view(), name='edit_playlist'),
    path('playlist/<slug:playlist_name_slug>/edit_playlist/add_song/', views.AddSongView.as_view(), name='add_song'),
    path('playlist/<slug:playlist_name_slug>/edit_playlist/remove_song/', views.RemoveSongView.as_view(), name='remove_song'),
    path('playlist/<slug:playlist_name_slug>/edit_playlist/delete_playlist/', views.DeletePlaylistView.as_view(), name='delete_playlist'),
    path('playlist/<slug:playlist_name_slug>/import/', views.ImportPlaylistView.as_view(), name='import_playlist'),
    path('search_spotify/', views.SearchSpotifyView.as_view(), name='search_spotify'),
    path('register_profile/', views.RegisterProfileView.as_view(), name='register_profile'),
    path('profile/<username>/', views.ProfileView.as_view(), name='profile'),
    path('profile/<username>/my_stats/', views.MyStatsView.as_view(), name='my_stats'),
    path('publish_playlist/', views.PublishPlaylistView.as_view(), name='publish_playlist'),
    path('suggest_tag/', views.TagSuggestionView.as_view(), name='suggest_tag'),
    path('suggest_playlist/', views.PlaylistSuggestionView.as_view(), name='suggest_playlist'),
    path('filter_playlists/', views.PlaylistFilterView.as_view(), name='filter_playlists'),
    path('add_new_song_details/', views.AddSongDetailView.as_view(), name='add_new_song_details'),
]

choonz_project/urls.py
from django.contrib import admin
from django.urls import path, include
from choonz import views
from django.conf import settings
from django.conf.urls.static import static
from registration.backends.simple.views import RegistrationView
from django.urls import reverse
from django.conf.urls import include
from django.contrib import admin


class MyRegistrationView(RegistrationView):
    def get_success_url(self, user):
        return reverse('choonz:register_profile')


urlpatterns = [
                  path('', views.IndexView.as_view(), name='index'),
                  path('choonz/', include('choonz.urls')),  # maps any URL beginning choonz/ to choonz app
                  path('admin/', admin.site.urls),
                  path('accounts/register/', MyRegistrationView.as_view(), name='registration_register'),
                  path('accounts/', include('registration.backends.simple.urls')),
                  path('oauth/', include('social_django.urls', namespace='social')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

choonz/forms.py
from django import forms
from django.contrib.auth.models import User
from choonz.models import Playlist, UserProfile, Rating
from datetime import datetime

class PlaylistForm(forms.ModelForm):
    name = forms.CharField(max_length=Playlist.max_length_char, help_text="Please enter the playlist name.")
    description = forms.CharField(max_length=Playlist.max_length_char * 2, help_text="Describe your playlist...",
                                  required=False)#
    slug = forms.CharField(widget=forms.HiddenInput(), required=False)
    createdDate = forms.DateTimeField(widget=forms.HiddenInput(), initial=datetime.now, required=False)
    lastUpdatedDate = forms.DateTimeField(widget=forms.HiddenInput(), initial=datetime.now, required=False)
    tags = forms.CharField(max_length=Playlist.max_length_char,
                           help_text="Enter tags to help people find your playlist!", required=False)

    # Meta is an inline class to provide addition info
    class Meta:
        # Associate ModelForm and a model (in this case, Playlist)
        model = Playlist
        fields = ('name', 'description', 'createdDate', 'lastUpdatedDate', 'tags',)


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password',)


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('picture',)


class RatingForm(forms.ModelForm):
    stars = forms.FloatField(max_value=5.0, min_value=0.0, required=True,
                             error_messages={'required': 'Star value must be between 0.0 and 5.0!'})
    comment = forms.CharField(max_length=Playlist.max_length_char * 2,
                              help_text="What did you think of this playlist...", required=True,
                              error_messages={'required': 'A blank comment gives no feedback to the creator!'})

    class Meta:
        model = Rating
        fields = ('stars', 'comment')

choonz/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.urls import reverse
from choonz.models import Playlist, UserProfile, Song, Rating, Tag, Artist
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from choonz.forms import PlaylistForm, UserProfileForm, RatingForm
from choonz.templatetags import choonz_template_tags
from datetime import datetime, timedelta
import pytz
import collections
from django.views import View
from django.utils.decorators import method_decorator
from django.template.defaultfilters import slugify
import spotipy
import json
from spotipy.oauth2 import SpotifyClientCredentials
from django.conf import settings
from django.db.models import Avg, Count

'''

    Index View

'''


class IndexView(View):
    def get(self, request):
        user_profile = get_user_profile(request)
        num_playlists_in_filter = 8

        # Playlists are split into most rated, highest rated and recently created for Index Page
        most_rated_playlists = Playlist.objects.annotate(num_ratings=Count('rating')).order_by('-num_ratings')[
                               :num_playlists_in_filter]
        highest_rated_playlists = Playlist.objects.annotate(
            average_rating=Avg('rating__stars')).order_by('-average_rating')
        recently_created_playlists = Playlist.objects.all().order_by('-createdDate')[:num_playlists_in_filter]

        # Highly rated are split into weekly/monthly
        this_week = datetime.today() - timedelta(days=7)
        this_month = datetime.today() - timedelta(days=31)
        playlists_this_week = highest_rated_playlists.filter(createdDate__gte=this_week)[:num_playlists_in_filter]
        playlists_this_month = highest_rated_playlists.filter(createdDate__gte=this_month)[:num_playlists_in_filter]

        context_dict = {'boldmessage': 'Crunchy Tunes, Creamy Beats, Cookie Music Tastes, Like A Candy Treat!',
                        'most_rated_playlists': most_rated_playlists,
                        'highest_rated_playlists': highest_rated_playlists[:num_playlists_in_filter],
                        'playlists_this_week': playlists_this_week,
                        'playlists_this_month': playlists_this_month,
                        'recent_playlists': recently_created_playlists, 'user_profile': user_profile}

        # return rendered response to send to the client
        response = render(request, 'choonz/index.html', context=context_dict)
        return response


'''

    About View

'''


class AboutView(View):
    def get(self, request):
        user_profile = get_user_profile(request)
        context_dict = {'user_profile': user_profile}
        visitor_cookie_handler(request)
        context_dict['visits'] = request.session['visits']

        return render(request, 'choonz/about.html', context_dict)


class ContactView(View):
    def get(self, request):
        user_profile = get_user_profile(request)
        context_dict = {'user_profile': user_profile}

        return render(request, 'choonz/contact.html', context_dict)


'''

    Playlist Views Section

'''


class ShowPlaylistView(View):
    # Helper method creates context dictionary with Playlist/User details
    def create_context_dict(self, playlist_name_slug, request):
        user_profile = get_user_profile(request)
        context_dict = {'user_profile': user_profile}
        user = request.user
        context_dict['user'] = user
        try:
            # find playlist from slug?
            playlist = Playlist.objects.get(slug=playlist_name_slug)

            # retrieve all users in this playlist (using filter())
            songs = Song.objects.filter(playlist=playlist)

            # Add results to context dict
            context_dict['songs'] = songs

            # Also add playlist to verify (in the template) it exists
            context_dict['playlist'] = playlist

            all_ratings = Rating.objects.filter(playlist_id=playlist.id)
            context_dict['ratings'] = all_ratings

            # All Ratings the profile owner has given
            try:
                ratings_by_user = list(Rating.objects.filter(user=user).values_list("playlist", flat=True))
                if playlist.id in ratings_by_user:
                    context_dict['user_has_rated'] = True
                    rating = Rating.objects.get(playlist=playlist, user=user)
                    context_dict['rating'] = rating
                else:
                    context_dict['user_has_rated'] = False
            except:
                context_dict['user_has_rated'] = None
                context_dict['rating'] = None
        except Playlist.DoesNotExist:
            context_dict['playlist'] = None
            context_dict['songs'] = None
            context_dict['user_has_rated'] = None
            context_dict['rating'] = None
            context_dict['ratings'] = None

        return context_dict

    # Viewing a playlist does not require a login
    def get(self, request, playlist_name_slug):
        context_dict = self.create_context_dict(playlist_name_slug, request)
        return render(request, 'choonz/playlist.html', context_dict)

    # Posting a rating does require a login
    @method_decorator(login_required)
    def post(self, request, playlist_name_slug):
        context_dict = self.create_context_dict(playlist_name_slug, request)

        return render(request, 'choonz/playlist.html', context_dict)


class AddPlaylistView(View):
    @method_decorator(login_required)
    def get(self, request):
        user_profile = get_user_profile(request)
        context_dict = {'user_profile': user_profile}
        form = PlaylistForm()
        context_dict['form'] = form
        return render(request, 'choonz/add_playlist.html', context_dict)

    @method_decorator(login_required)
    def post(self, request):
        form = PlaylistForm(request.POST)
        user_profile = get_user_profile(request)
        context_dict = {'user_profile': user_profile}

        # is the form valid?
        if form.is_valid():
            playlist = form.save(commit=False)
            playlist.creator = request.user
            playlist.save()
            if request.POST.get('tags'):
                tag_string = request.POST.get('tags')
                tag_string = tag_string.replace(', ', ',')
                tag_list = tag_string.split(',')
                for t in tag_list:
                    if t:
                        found_tag = Tag.objects.get(description=t)
                        playlist.tags.add(found_tag)
                playlist.save()
            # redirect back to index
            return redirect(reverse('choonz:edit_playlist', kwargs={'playlist_name_slug': playlist.slug}))
        else:
            # form contained errors
            # print them to the terminal
            print(form.errors)
        context_dict['form'] = form

        return render(request, 'choonz/add_playlist.html', context_dict)


class PlaylistEditorView(View):
    @method_decorator(login_required)
    def get(self, request, playlist_name_slug):
        user_profile = get_user_profile(request)
        playlist = Playlist.objects.get(slug=playlist_name_slug)

        # Give user opportunity to edit any of their own playlists
        playlist_list = Playlist.objects.filter(creator=request.user)

        context_dict = {'user_profile': user_profile, 'playlist': playlist, 'playlist_name_slug': playlist_name_slug,
                        'playlist_list': playlist_list}

        return render(request, 'choonz/edit_playlist.html', context_dict)

    @method_decorator(login_required)
    def post(self, request, playlist_name_slug):
        playlist = Playlist.objects.get(slug=playlist_name_slug)

        # Response dictionary used to flag whether playlist edit was successful or not
        response_dict = {'status': False}

        # Trying to edit the playlist name
        if request.POST.get('playlist_name'):
            new_name = request.POST.get('playlist_name')
            playlist.name = new_name
            try:
                playlist.save()
            except:
                response_dict['message'] = "Playlist name already exists!"
                return HttpResponse(json.dumps(response_dict), content_type="application/json")

        # Editing the playlist description
        if request.POST.get('playlist_description'):
            new_description = request.POST.get('playlist_description')
            playlist.description = new_description
            try:
                playlist.save()
            except:
                # Description doesn't need to be unique, but there could be a database error
                print("description error")

        # If tags are being updated
        if request.POST.get('playlist_tags'):
            # Process tag string
            new_tags = request.POST.get('playlist_tags')
            tag_string = new_tags.replace(', ', ',')
            tag_list = tag_string.split(',')
            for t in tag_list:
                # Search for each tag in database
                if t:
                    found_tag = Tag.objects.get(description=t)
                    playlist.tags.add(found_tag)
            try:
                # Clear old tags, save
                playlist.tags.clear()
                playlist.save()
            except:
                response_dict['message'] = "Invalid tags!"
                return HttpResponse(json.dumps(response_dict), content_type="application/json")

        response_dict['status'] = True
        response_dict['message'] = "Playlist details updated"
        return HttpResponse(json.dumps(response_dict), content_type="application/json")


class AddSongDetailView(View):
    @method_decorator(login_required)
    def get(self, request):
        playlist_slug = request.GET['playlist_slug']
        song_slug = request.GET['song_slug']

templates/choonz/about.html
{% extends 'choonz/base.html' %}
{% load staticfiles %}

{% block title_block %}
	About choonz
{% endblock %}

{% block body_block %}
	<div class="jumbotron p-4">
		<div class="container">
			<h1 class="jumbotron-heading"><strong>What are Choonz?</strong></h1>
			<div>
				<h2 class="h2">
				Here what it's all about.
				<br>
				Choonz is brought to you by the GrooPeez
				</h2>
			</div>
			<p>
			<br>
			<br>
			Choonz is a django based web application, created by four music loving students as part of their Glasgow University Masters Degree in Software Development. 
			<br>
			<br>
			Choonz allows users to create, upload or share music playlists from their favourite streaming sources. Create a new playlist and apply descriptive ‘tags’ to help categorise the playlist. Other users will then be able to rate and review your playlist/s and will be recommended similar popular playlists.
			<br>
			<br>
			Our top rated playlists are displayed on the front page. You can find the playlists with the most ratings, recently created playlists as well as the highest rated of the last week, month and all time. If this isn't to your taste you can also search for playlists by name or by tag/s, helping you find your perfect playlist!
			<br>
			<br>
			Sign in with Github, Spotify or Twitter and automatically share or import you favourite playlists. Friends can then rate your musical prowess. 
			<br>
			<br>
			Create, rate and debate music with Choonz.
			<br>
			<br>
			</p>
			<br>
			<br>	
			<p>Visits: {{ visits}}</p>
			</div>
		</div>
	<div>

	</div>
{% endblock %}

templates/choonz/add_page.html
{% extends 'choonz/base.html' %}
{% load staticfiles %}

{% block title_block %}
	Add a Page
{% endblock %}

{% block body_block %}
	<div class="jumbotron p-4">
		<div class="container">
			<h1 class="jumbotron-heading">Add a Page to {{ playlist.name }}</h1>
		</div>
	</div>
	<div class="container">
		<div class="row">
			<form role="form" id="page_form" method="post" action="{% url 'choonz:add_page' playlist.slug %}">
				{% csrf_token %}
				{% for hidden in form.hidden_fields %}
					{{ hidden }}
				{% endfor %}
				{% for field in form.visible_fields %}
					{{ field.errors }}
					{{ field.help_text }}
					{{ field }} <br />
					<div class="p-2"></div>
				{% endfor %}
				<br />
				<button class="btn btn-primary" type="submit" name="submit">Add Page </button>
				<div class="p-5"></div>
			</form>
		</div>
	</div>
{% endblock %}

templates/choonz/categories.html
<ul class="nav flex-column">
	{% if playlists %}
		{% for c in playlists %}
			{% if c == current_playlist %}
				<li class="nav-item"><a class="nav-link active" href="{% url 'choonz:show_playlist' c.slug %}"><span data-feather="archive"></span>{{ c.name }}</a></li>
			{% else %}
				<li class="nav-item"><a class="nav-link active" href="{% url 'choonz:show_playlist' c.slug %}"><span data-feather="archive"></span>{{ c.name }}</a></li>
			{% endif %}
		{% endfor %}
	{% else %}
		<li class="nav-item"><strong>There are no playlists present.</strong></li>
	{% endif %}
</ul>

templates/choonz/import_playlist.html
{% extends 'choonz/base.html' %}
{% load staticfiles %}
{% load choonz_template_tags %}

{% block title_block %}
    Import a Playlist
{% endblock %}

{% block body_block %}
    <div class="container-fluid" id="headerContainer">
        <h1 class="display-4" id="titleHeader">Choonbuilder - Import Choonz</h1>
        <p class="lead"></p>
    </div>

    <div class="card text-center">
        <div class="card-header">
            <ul class="nav nav-tabs card-header-tabs">
                <li class="nav-item">
                    <a class="nav-link active" href="{% url 'choonz:add_playlist' %}">Add a Playlist</a>
                </li>
                {% if playlist %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'choonz:edit_playlist' playlist.slug %}">Edit a Playlist</a>
                </li>
                {% endif %}
            </ul>
        </div>
        <div class="container">
            <br />
            <h3 class="card"> Import a playlist from Spotify</h3>
            <div class="row">
                <div class="container">
                <form role="form" id="import_playlist_form" method="post" action="{% url 'choonz:import_playlist' playlist.slug %}">
                    {% csrf_token %}
                    {% for hidden in form.hidden_fields %}
                        {{ hidden }}
                    {% endfor %}
                    <div class="card-body">
                        <div class="input-group mb-3">
                            <p class="required">
                                <div class="input-group-prepend">
                                    <span class="input-group-text" id="playlist-name-prompt">Spotify username:</span>
                                </div>
                                <input type="text" name="spotify_username" id="spotify_username" class="form-control" placeholder="Spotify username" required autofocus size="50">
                            </p>
                        </div>
                        <div class="input-group mb-3">
                            <p class="required">
                                <div class="input-group-prepend">
                                    <span class="input-group-text" id="playlist-description-prompt">Spotify playlist name:</span>
                                </div>
                                <input type="text" name="spotify_playlist_name" id="spotify_playlist_name" class="form-control" placeholder="Spotify playlist name" size="100">
                            </p>
                        </div>
                    <button class="btn btn-primary" type="submit" data-playlistSlug="{{ playlist.slug }}" name="submit">Import Playlist</button>
                    </div>
                </form>
            </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/choonz/list_profiles.html
{% extends 'choonz/base.html' %}
{% load staticfiles %}

{% block title_block %}
	User Profiles
{% endblock %}

{% block body_block %}
	
	<div class="jumbotron p-4">
		<div class="container">
			<h1 class="jumbotron-heading">User Profiles</h1>
		</div>
	</div>

	<div class="container">
		<div class="row">
			{% if user_profile_list %}
			<div class="panel-body">
				<div class="list-group">
					{% for list_user in user_profile_list %}
						<div class="list-group-item">
							<h4 class="list-group-item-heading">
								<a href="{% url 'choonz:profile' list_user.user.username %}">{{ list_user.user.username }}
								</a>
								{% if list_user.picture %}
									<img src="{{ MEDIA_URL }}{{ list_user.picture }}" width="30" height="30" alt="{{ list_user.username }}'s profile image" />
								{% else %}
									<img src="http://lorempixel.com/30/30" width="30" height="30" alt="No profile image" />
								{% endif %}
							</h4>
						</div>
					{% endfor %}
				</div>
			</div>
			{% else %}
				<p>There are no users present on choonz.</p>
			{% endif %}
		</div>
	</div>

{% endblock %}

templates/choonz/page_listing.html
{% if pages %}
	<ul>
		{% for page in pages %}
			<li><a href="{% url 'choonz:goto' %}?page_id={{page.id}}">{{ page.title }}</a>
			{% if page.views > 1 %}
                ({{ page.views }} views)
            {% elif page.views == 1 %}
                ({{ page.views}} view)
            {% endif %}
        </li>
		{% endfor %}
	</ul>
{% else %}
	<strong>No pages currently in playlist.</strong>
{% endif %}

templates/choonz/playlist.html
{% extends 'choonz/base.html' %}
{% load staticfiles %}
{% load choonz_template_tags %}

{% block title_block %}
	{% if playlist %}
		{{ playlist.name }}
	{% else %}
		Unknown Playlist
	{% endif %}
{% endblock %}

{% block body_block %}
	{% if playlist %}
		<div class="container page-header p-2">
			<div class="container m-1">
				<div class="row">	
				<div class="col">
					<div class="row">	
						<h1 class="container page-header-font">{{ playlist.name }}</h1>
					</div>
					<p>created by <a href="{% url 'choonz:profile' playlist.creator %}">{{ playlist.creator }}</a></p>
					<div class="row">
						<strong>Description: {{ playlist.description }}<br/></strong>
						Created on: {{ playlist.createdDate }}, Last updated: {{ playlist.lastUpdatedDate }}
					</div>
				</div>	
				<div class="col">
					<div class="row">
						<h4 class="container page-header-font">Average Rating: 
						{% if playlist.get_average_rating %}
							{{ playlist.get_average_rating|floatformat}}
						{% else %}
							0.0
						{% endif %}
						/5.0</h4>
					</div>
					<div class="row">
						{% if user.is_authenticated %}
							{% if user != playlist.creator %}
								<div class="page-header p-2">
									<form class="form-inline" id="rating-form" method="post" action="{% url 'choonz:rate_playlist' playlist.slug %}">
									{% csrf_token %}
									{{ form.non_field_errors }}
									<div class="row centred mb-3">
		                                <p class="required">
		                                    <div class="input-group-prepend">
		                                        <span class="input-group-text">Your rating: </span>
		                                    </div>
		                                {% if user_has_rated %}
		                                    <div class="rate" id="stars" data-rate-value={{rating.stars}}></div>
		                                    <input type="text" name="stars" id="stars-input" value="{{rating.stars}}" hidden />
		                                {% else %}
		                                	<div class="rate" id="stars" data-rate-value={{rating.stars}}></div>
		                                    <input type="text" name="stars" id="stars-input" value="0" hidden />
		                                {% endif %}
		                                    <div class="text-danger">
						                            {{ form.stars.errors }}
						                    </div>
		                                </p>
		                            </div>

									<div class="row centred mb-3">
		                                <p class="required">
		                                    <div class="input-group-prepend">
		                                        <span class="input-group-text">Comment: </span>
		                                    </div>
		                                    {% if user_has_rated %}
		                                    	<input type="text" name="comment" id="comment" class="form-control" value="{{ rating.comment }}" size="50" readonly />
		                                    {% else %}
		                                    	<input type="text" name="comment" id="comment" class="form-control" value="" size="50" />
		                                    {% endif %}
		                                </p>
		                            </div>
		                            <div class="text-danger">
				                            {{ form.comment.errors }}
				                    </div>
				                    <div class="container-fluid">
				                  	{% if user_has_rated %}
				                    	<a type="button" class="btn btn-warning btn-block" id="show-update-rating-fields">Edit Your Rating</a>
				                    	<button class="btn btn-primary btn-block" id="hidden-submit-rating-update" type="submit">Submit</button>
										<a type="button" class="btn btn-secondary btn-block" id="hidden-cancel-rating-update">Cancel</a>
				                    {% else %}
				                    	<button class="btn btn-primary btn-block" id="submit-rating-update" type="submit">Submit</button>
										<a type="button" class="btn btn-secondary btn-block" id="cancel-rating-update">Cancel</a>
									{% endif %}
									</div>
									</form>
								</div>
							{% else %}
								{% if playlist.public %}
									<div class="page-header p-2">
										<form class="form-inline" id="user-form" method="get" action="{% url 'choonz:publish_playlist' %}">
											{% csrf_token %}
											<input id="playlist_id" name="playlist_id" type="hidden" value="{{ playlist.id }}">
											<button class="btn btn-warning btn-block m-1" type="submit" data-playlist_id="{{ playlist.id }}" name="submit">Send to Drafts</button>
										</form>
									</div>
								{% else %}
									<div class="row page-header p-2">
										<div class="col p-1">
											<form class="form-inline" id="user-form" method="post" action="{% url 'choonz:publish_playlist' %}">
												{% csrf_token %}
												<input id="playlist_id" name="playlist_id" type="hidden" value="{{ playlist.id }}">
												<button class="btn btn-warning btn-block m-1" type="submit" data-playlist_id="{{ playlist.id }}" name="submit">Publish this Playlist!</button>
											</form>
										</div>
										<div class="col p-1">
											<a class="btn btn-info btn-block m-1 mr-2" href="{% url 'choonz:edit_playlist' playlist.slug %}">Edit Playlist</a>
										</div>
									</div>
								{% endif %}
							{% endif %}
						{% endif %}
					</div>
				</div>
				</div>
			</div>
		</div>
		
		<div class="container page-header">
			<h3 class="container page-header-font">Tags on this Playlist</h3>
			<div class="container" id="tag-listing">
	            {% block sidebar_block %}
	                {% get_tag_list playlist %}
	            {% endblock %}
	        </div> 
	    </div>
		
		<div class="container page-header">
			<h3 class="container page-header-font">Track List</h3>
			{% if songs %}
			<div class="container" id="songs-listing">
				<div class="container">
					{% for song in songs %}
					<li class="choonz-row badge-light">
						<div class="col-md-7">
							<div class="col">
								<div class="centred-left-indent-5 row">
									<h5>{{ song.title }}</h5>
								</div>
								<div class="centred-left-indent-10 row">
									<span>by {{ song.artist }}</span>
								</div>
							</div>
						</div>
						<div class="col-md-5">
							<div class="choonz-col">
							{% if song.linkToSpotify %}
								<a class="btn btn-primary" href="{{ song.linkToSpotify }}" target="_blank" name="submit">Listen with Spotify</a>
							{% else %}
								<span class="badge badge-dark">User has not provided a link to this song</span>
							{% endif %}
							{% if song.linkOther %}
								<a class="btn btn-primary" href="{{ song.linkOther }}" target="_blank" name="submit">Listen Online</a>
							{% endif %}
							</div>
						</div>
					</li>
					{% endfor %}
				</div>
			</div>
		</div>

		<div class="container page-header">
			<h3 class="container page-header-font">Ratings for {{ playlist.name }}</h3>
			<div class="container">
				{% if ratings %}
				<div id="rating-listing">
					{% for rating in ratings %}
					<li class="list-group-item see-through">{{ rating.stars }} &#x2606; - "{{ rating.comment }}" ~ 
						<a href="{% url 'choonz:profile' rating.user.username %}">{{ rating.user.username }} </a>
						<span class="badge badge-light">submitted on {{rating.date}}</span>
					</li>
					{% endfor %}
				</div>
				{% else %}
					<div class="container">
						<strong>No ratings for current playlist.</strong>
					</div>
				{% endif %}
			</div>
			{% else %}
			<div class="container">
				{% if user.is_authenticated %}
					{% if user != playlist.creator %}
						<div class="container">
							<strong>No songs currently in playlist.</strong>
						</div>
					{% else %}
						<div class="container">
							<p><strong>Your playlist is looking a little bare! People can't rate it when it's empty!</strong></p>
							<ul>
								<li class="see-through">Why not <a href="{% url 'choonz:edit_playlist' playlist.slug %}">add some songs</a>?</li>
								<li class="see-through">Or you could <a href="{% url 'choonz:import_playlist' playlist.slug %}">import a playlist from Spotify</a>?</li>
							</ul>
						</div>
					{% endif %}
				{% else %}
					<div class="container">
						<strong>No songs currently in playlist.</strong>
					</div>
				{% endif %}
			</div>
			{% endif %}

		{% else %}
			The specified playlist does not exist.
		{% endif %}
		</div>
{% endblock %}